language: node_js
node_js:
- '8'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "bCXjKP3DP/8AsvVie18pEd2q0Ozs4x2EaoBlanL/1pSdQb7HlPHpSWlwL4SJWZHagBbMhQ/hO6PHYKXf+1fBBkCxNoVYQ+/cgo+xQuqST24yfTYub3jW4HyXEhFbGjoGqMyMIm03CZupbcJ83c1HajPs2tKikE5gYpiL8BPLjto4erogX3HhG8lgIB3GUgDVvySfNBldmu0MnF2+CnzsECi14sA9/SKz4vpNMrbsavCl2PqTlt8jaJ9Bmx4vr5tre2CCr1kPhPaOVLsGxJDCSh2CRvYWKLBfdxoeNDj4dIOt3hg+WOaaAfFiQJRe5Z9Mjg1po+vu+c6qsoUWK/kb2b8wrcOMEBmBczIymHtYE2IYQrf8NBcLoFWCTC8gYHXgzP/PAUxu9JFa2bwDQ8A0HKuO9IpceopvfBzcsyjs5suQ3rRYe1anHQxtv4jr7pOV6U6pq3wAapgeR8HKpnS9oTcRpwmWV2AmTkyKH4Mwlig44QqPBz+3xYRyqM1VHLlUj6GxsBiduOcLzveGx3xhVXnHrSzAlVE8MgyPw8IKY4ImC3u34feuVSyPX02d8KDgxI9Lls0H/qEQn9oGLOTMWc2yPQIZsZqwYXPPWH8Psy6ARp+4tv6u6kdt+m7fh8bBfzR3joI62UD0IPWn/ciiviOKUkAnrQMGSbqflHWu3Zk="
